name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # allows manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Step 3: Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --info

      # Step 5: Create timestamp variable
      - name: Set timestamp
        id: ts
        run: echo "TS=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      # Step 6: Create or update GitHub Release with APK
      - name: Upload APK to Release
        uses: ncipollo/release-action@v1
        with:
          tag: "build-${{ github.run_number }}"      # auto-incremented tag per workflow run
          name: "APK ${{ env.TS }}"                  # name in release
          files: app/build/outputs/apk/debug/app-debug.apk
